### ISSUE TITLE
sampling_timesteps and training time

### ISSUE THREAD

**Issue by liziwei-0** [liw95/DiffLoc#1]
Hello, thank you for your great work on this project! 
Can you provide table data for different "sampling_timesteps"? How long is this model trained on which graphics card?

**Comment by liw95** [comment]
Hi, thank you for your questions.

1. Table 6 of the paper shows the running time of different sample steps. 
2. We train the model using 4 RTX 3090 GPUs for about 2 days.

**Comment by liziwei-0** [comment]
Thank you for your reply. Does training and inference in your work involve selecting adjacent frame point cloud images for computation? Can a model without geometric constraints yield reasonable results?

**Comment by liw95** [comment]
Hi, 
1. As we described in Sec. 4.1 that  the input point cloud sequence is a tuple of size 3
with a spacing of 2 frames. The input feature dimension of the denoiser is  [B, 3, C]. 
2. Since the denoiser requires some feature fitting capability, we used the Transformer implementation. Therefore, we do not attempt to use a single-frame input.
3. You could try using a single-frame input and simply replacing the denoiser with a structure such as a fully-connected network, which would significantly speed up training.

**Comment by liziwei-0** [comment]
Hello, I am trying to run your code. How did you select the training and validation sets in the two datasets?I have downloaded the NCLT dataset, but I am not sure how to process it to make it run correctly.

**Comment by liw95** [comment]
Hi, for the NCLT dataset, we provide the nclt_precess.py for data preparation. You need that (1) download the sequences of  2012-02-12, 2012-02-19, 2012-03-31, 2012-05-26 and (2) organize the data format as described in the dataset of readme, and (3) run the nclt_precess.py. Then, you can run the test.py for evaluation. If you have any questions, for convenience, you can add my wechat: ytkl303628114.
